// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Banner.tsx";
import * as $$$$$$1 from "./sections/Florumparfum.tsx";
import * as $$$$$$2 from "./sections/Footer.tsx";
import * as $$$$$$3 from "./sections/Header.tsx";
import * as $$$$$$4 from "./sections/Hero.tsx";
import * as $$$$$$5 from "./components/ui/RecommendedPerfume.tsx";
import * as $$$$$$6 from "./sections/Theme/Theme.tsx";
import * as $$$$$$7 from "./sections/West/Westperfum.tsx";

const manifest = {
  "sections": {
    "site/sections/Banner.tsx": $$$$$$0,
    "site/sections/Florumparfum.tsx": $$$$$$1,
    "site/sections/Footer.tsx": $$$$$$2,
    "site/sections/Header.tsx": $$$$$$3,
    "site/sections/Hero.tsx": $$$$$$4,
    "site/sections/RecommendedPerfume.tsx": $$$$$$5,
    "site/sections/Theme/Theme.tsx": $$$$$$6,
    "site/sections/West/Westperfum.tsx": $$$$$$7,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
