// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/AquaAllegoria/FeraGranitaPerfum.tsx";
import * as $$$$$$1 from "./sections/Banner.tsx";
import * as $$$$$$2 from "./sections/BasicsPerfums/D&GPerfum.tsx";
import * as $$$$$$3 from "./sections/BasicsPerfums/FloralPerfum.tsx";
import * as $$$$$$4 from "./sections/BasicsPerfums/WindPerfum.tsx";
import * as $$$$$$5 from "./sections/Chanel/BleuDeChanelPerfum.tsx";
import * as $$$$$$6 from "./sections/Chanel/CocoNoirPerfum.tsx";
import * as $$$$$$7 from "./sections/Chanel/GabriellePerfum.tsx";
import * as $$$$$$8 from "./sections/Chanel/NumberFivePerfum.tsx";
import * as $$$$$$9 from "./sections/Dior/SauvagePerfum.tsx";
import * as $$$$$$10 from "./sections/Florumparfum.tsx";
import * as $$$$$$11 from "./sections/Footer.tsx";
import * as $$$$$$12 from "./sections/Header.tsx";
import * as $$$$$$13 from "./sections/HeaderUserPage.tsx";
import * as $$$$$$14 from "./sections/Hero.tsx";
import * as $$$$$$15 from "./sections/RecommendedPerfumeSection.tsx";
import * as $$$$$$16 from "./sections/Theme/Theme.tsx";
import * as $$$$$$17 from "./sections/West/Westperfum.tsx";

const manifest = {
  "sections": {
    "site/sections/AquaAllegoria/FeraGranitaPerfum.tsx": $$$$$$0,
    "site/sections/Banner.tsx": $$$$$$1,
    "site/sections/BasicsPerfums/D&GPerfum.tsx": $$$$$$2,
    "site/sections/BasicsPerfums/FloralPerfum.tsx": $$$$$$3,
    "site/sections/BasicsPerfums/WindPerfum.tsx": $$$$$$4,
    "site/sections/Chanel/BleuDeChanelPerfum.tsx": $$$$$$5,
    "site/sections/Chanel/CocoNoirPerfum.tsx": $$$$$$6,
    "site/sections/Chanel/GabriellePerfum.tsx": $$$$$$7,
    "site/sections/Chanel/NumberFivePerfum.tsx": $$$$$$8,
    "site/sections/Dior/SauvagePerfum.tsx": $$$$$$9,
    "site/sections/Florumparfum.tsx": $$$$$$10,
    "site/sections/Footer.tsx": $$$$$$11,
    "site/sections/Header.tsx": $$$$$$12,
    "site/sections/HeaderUserPage.tsx": $$$$$$13,
    "site/sections/Hero.tsx": $$$$$$14,
    "site/sections/RecommendedPerfumeSection.tsx": $$$$$$15,
    "site/sections/Theme/Theme.tsx": $$$$$$16,
    "site/sections/West/Westperfum.tsx": $$$$$$17,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
